### PR TITLE
Add CRUD routes to React generator

### PR DESCRIPTION
**Pull request by sjhuang26**
Note that in a path such as /todos/5/edit, the "5" is read from the URL and displayed on the page.

### CODE REVIEW

**Comment by aeksco** [comment]
Great start! To fully resolve #36 let's add the following components and link them to those CRUD routes:
`<TodoList />`
`<TodoNew />`
`<TodoShow />`
`<TodoEdit />`

**Comment by sjhuang26** [comment]
I added the requested components, as well as moving component edit functionality into a separate component TodoEditor.

**Comment by aeksco** [comment]
Nice work! I'll link the components to their respective routes once this is merged in

**Comment by sjhuang26** [comment]
Looks like I forgot to commit the part of my work that properly links the components to routes. I'll take care of this.

**Pull request merged**
